meta:
  source_loader:
    path: "{{pipeline_path}}"

tasks:

  - name: copy
    source: scripts/scp.sh
    product: 
      output_read1: "{{cwd}}/read1.fastq"
      output_read2: "{{cwd}}/read2.fastq"
    params:
      remote_path: "{{remote_path}}"
      user: "{{user}}"
      url: "{{url}}"
      input_read1: "{{input_read1}}"
      input_read2: "{{input_read2}}"

  - source: quality
    source: scripts/quality.sh
    product: 
      output_read1: "{{cwd}}/read1.qc.fastq"
      output_read2: "{{cwd}}/read2.qc.fastq"
      log: "{{cwd}}/log.quality.txt"
    params: 
      primers: "{{primers}}"
      quality_threshold: "{{quality_threshold}}"
      threads: "{{threads}}"

  - name: classify
    source: scripts/classify.sh
    params:
      kraken_db: "{{kraken_db}}"
      kraken_threads: "{{kraken_threads}}"
    product:
      kraken_out: "{{cwd}}/classification.csv"
      log: "{{cwd}}/log.classify.txt"

  - name: filter-host
    source: notebooks/filter-host.ipynb
    params: 
      domains: "{{domains}}"
    product:
      csv: "{{cwd}}/taxon-filter.csv"
      nb: "{{cwd}}/out.filter-host.ipynb"

  - name: remove-host
    source: scripts/remove-host.sh
    product:
      output_read1: "{{cwd}}/read1.fqc.fastq"
      output_read2: "{{cwd}}/read2.fqc.fastq"
      log: "{{cwd}}/log.taxon-filter.txt"

  - source: flash
    source: scripts/flash.sh
    product: 
      output_contig: "{{cwd}}/contig.fastq"
      log: "{{cwd}}/log.flash.txt"
    params: 
      threads: "{{threads}}"

  - source: mmseqs-create-db
    source: scripts/mmseqs-create-db.sh
    product: 
      log: "{{cwd}}/log.mmseqs-db.txt"
      db: "{{cwd}}/contigs"

  - source: mmseqs-map-taxonomy
    source: scripts/mmseqs-map-taxonomy.sh
    product: 
      tsv: "{{cwd}}/{{library_name}}.taxonomy.tsv"
      html: "{{cwd}}/{{library_name}}.taxonomy.html"
      log_search: "{{cwd}}/logs.mmseqs-taxonomy.txt"
      log_tsv: "{{cwd}}/logs.mmseqs-tsv.txt"
      log_report: "{{cwd}}/logs.mmseqs-report.txt"
    params: 
      ref_db_path: "{{ref_db_path}}"
      name: "{{cwd}}/{{library_name}}"